S03 us14
WildCodeSchool/orleans-php-2003-project-easterapp pull request #101
Opened 2020-06-17 12:59 UTC by mayard689

This manage the features display according to the requested estimation.

This does not manage the total load calculation estimation by estimation (so the current total load is the load for all features for all estimations)

This dos not manage the estimation selection when adding a feature. A default behaviour is set to add a feature to all estimations.

This does not manage the estimation selection when removing a feature (so it is removed from all estimations)

2020-06-18 07:59 UTC, dierickd approved these changes

2020-06-18 19:22 UTC, sblondeau requested changes

2020-06-18 19:22 UTC, sblondeau commented on src/Entity/ProjectFeature.php
> +     * @ORM\Column(type="boolean")
manque les assert type boolean

2020-06-18 19:22 UTC, sblondeau commented on templates/project/edit.html.twig
> +        {{ form_end(form, {'render_rest': false}) }}
hum tu as sans doute une bonne raison de faire ça, quoi que je ne vois pas trop là. Mais surtout, je crois que ça ne prends pas le token csrf en compte si tu fais ça (mais j'ai un doute). A vérifier mais il faut qu'il soit là

2020-06-18 19:22 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +            {% if featureCategory.id == projectFeature.vars.data.category.id and attribute(projectFeature.vars.data, 'is'~variant) %}
je n'ai plus en tete ce sur quoi on était parti niveau bdd, mais là je comprends que tu boucles sur toutes les features d'un projet pour n'afficher que celle d'une variant ? (et a priori ça m'a échappé mais tu fais pareil pour les category :/) 
en fait ça fonctionne mais ce n'est pas optimisé car tu boucle sur TOUTES les features d'un projet pour n'en afficher qu'une partie. 
idéalement il faut plutot faire une requete personnalisé dans le Repository de l'entité en question, récupérer les infos "filtrée" (au niveau SQL du coup), les "mettre en forme, les regrouper par categ" (si besoin), ça ça peut etre fait dans un service, puis les afficher avec une simple boucle, sans ce if qui devient inutile. 
Peut-etre que je comprend mal ton idée après donc hésite pas à revenir vers moi si besoin

2020-06-19 06:56 UTC, mayard689 commented on templates/project/edit.html.twig
> +        {{ form_end(form, {'render_rest': false}) }}
La problematique ici est que je n'affiche plus toutes les fonctionnalités du projets mais seulement celles qui sont associées à la bonne variante de chiffrage. Si je ne supprime pas le form rest, alors je (enfin twig)  vais devoir transmettre toutes les fonctionnalité au navigateur en les cachant par du css. Pour le coup ça me semble pas super. Le csrf doit pouvoir etre sorti du form rest s'il est manipulé manuellement...

2020-06-19 06:59 UTC, mayard689 commented on templates/project/_featuresList.html.twig
> +            {% if featureCategory.id == projectFeature.vars.data.category.id and attribute(projectFeature.vars.data, 'is'~variant) %}
J'ai bien pensé à tout ça mais c'est le form type qui affiche la totalité de la collection. Si j'enleve cette collection du form type et que j'en met une personnalisée à la place, qu'advient il des liens entre cette nouvelle collection et le projet...et les fonctionnalités qui ne sont pas dans la collection personnalisée, il faut qu'ils restent connectés...

2020-06-29 13:25 UTC, merged