S03 us13 total charge
WildCodeSchool/orleans-php-2003-project-easterapp pull request #108
Opened 2020-06-18 07:37 UTC by benoitchocot

2020-06-18 08:19 UTC, dierickd requested changes

2020-06-18 08:19 UTC, dierickd commented on templates/project/_featuresList.html.twig
> +        {% endfor %}
il y a une faute d'orthographe. 
Pas de fonctionnalité enregistrée (sans s) ou
Pas de fonctionnalités enregistrées (avec un s pour les 2)

2020-06-18 08:45 UTC, mayard689 submitted a review, later dismissed

2020-06-18 08:45 UTC, mayard689 commented on templates/project/_featuresList.html.twig
> +        {% endfor %}
La correction du S est dans une des PR en attente..

2020-06-18 19:36 UTC, sblondeau requested changes

2020-06-18 19:36 UTC, sblondeau commented on src/Service/ProjectCalculator.php
>          //return
commentaire inutile, on voit bien qu'on a un return juste en dessous ;-)

2020-06-18 19:36 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +    public function calculateProjectLoadByCategory(Project $project, int $featureCategoryId): float
ça me gène cette méthode qui est quasi la meme que calculateProjectLoad. Ca peut se factoriser ;-)

2020-06-18 19:36 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +                if ($featureCategoryId == $feature->getCategory()->getId()) {
$feature n'a pas tjs une category ? dans tous les cas les deux if imbriqués peuvent s'écrire sur une ligne
            if ($feature->getCategory() !== null && $featureCategoryId == $feature->getCategory()->getId()) { .. .}

2020-06-18 19:36 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +    public function getVelocity(Project $project)
la velocity est amenée à etre calculée en dehors de la classe ? sinon plutot la mettre en private

2020-06-18 20:00 UTC, benoitchocot commented on src/Service/ProjectCalculator.php
> +    public function calculateProjectLoadByCategory(Project $project, int $featureCategoryId): float
Ca renvoie pas le même résultat, je pense pas que je puisse faire mieux que ça :/

2020-06-22 07:38 UTC, mayard689 submitted a review, later dismissed

2020-06-22 11:50 UTC, sblondeau requested changes

2020-06-22 11:50 UTC, sblondeau commented on src/Controller/FeatureController.php
> +    const MAX_PER_PAGE = 200;
200 par page ? t'as bien une pagination de gérer là ?

2020-06-22 11:50 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +                $load += $feature->getDay();
en fait ce qui pourrait peut etre etre fait, c'est de passer un param optionnel à getProjetFeatures($featureCategoryId)
et si y a pas de param, ça renvoit toutes les features, sinon que les features correspondant à ce categoryId.
et ainsi le if dans la boucle est plus nécessaire.
Ca serait plus optimisé (évite de charger toutes les features pour refiltrer après dans la boucle), plus simple à lire et permettrait d'enlever une des deux méthodes...

2020-06-22 12:23 UTC, benoitchocot commented on src/Controller/FeatureController.php
> +    const MAX_PER_PAGE = 200;
j'ai oublié de l'enlever, c'était pour vérifier quelque chose pendant le dev, c'est fix

2020-06-22 14:18 UTC, mayard689 submitted a review, later dismissed

2020-06-22 14:19 UTC, dierickd submitted a review, later dismissed

2020-06-22 15:24 UTC, sblondeau requested changes

2020-06-22 15:24 UTC, sblondeau commented on src/Controller/FeatureController.php
> +                    ['id' => 'DESC']
pourquoi par id plus que par name ?

2020-06-22 15:24 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +    public function calculateProjectLoad(Project $project, int $featureCategoryId = 0): float
a remodif, voir discussion sur slack

2020-06-22 15:26 UTC, benoitchocot commented on src/Controller/FeatureController.php
> +                    ['id' => 'DESC']
Suggestions du client pour récupérer les fonctionnalités en fonction de leur date d'ajout

2020-07-01 14:34 UTC, closed without merging