S03 us28 create user
WildCodeSchool/orleans-php-2003-project-easterapp pull request #109
Opened 2020-06-18 12:30 UTC by dante18

2020-06-18 13:05 UTC, dierickd submitted a review, later dismissed

2020-06-18 19:41 UTC, sblondeau requested changes

2020-06-18 19:41 UTC, sblondeau commented on assets/scss/user.scss
> +    color: #046077;
couleur en variable !

2020-06-18 19:41 UTC, sblondeau commented on src/Entity/User.php
> +     * @ORM\Column(type="string", length=255, nullable=true)
assert

2020-06-18 19:41 UTC, sblondeau commented on templates/user/new.html.twig
> +{% block title %}Big Bill | Nouvelle utilisateur{% endblock %}
Nouvel

2020-06-18 19:41 UTC, sblondeau commented on templates/user/new.html.twig
> +    <h1>Création d'un nouvelle utilisateur</h1>
nouvel

2020-06-18 19:41 UTC, sblondeau commented on templates/user/new.html.twig
> +            {{ include('user/_form.html.twig', {'buttonName': 'Crée le compte de l\'utilisateur'}) }}
"crée**r** le compte de l'utilisateur"  plutot ?

2020-06-18 19:41 UTC, sblondeau commented on src/Controller/UserController.php
> +            $user->setPassword(
si je comprends bien tu génères un mot de passe aléatoire à la crétation d'un compte user ? 
dans ce cas comment le user connait son mot de passe ? 
je dis pas qu'il faut enlever cette partie mais je veux etre sûr que vous avez prévu qq chose derrière dans une autre US pour que la personne puisse se connecter ! :p

2020-06-18 19:53 UTC, dante18 commented on src/Controller/UserController.php
> +            $user->setPassword(
On a prévue d'envoyer un mail contenant un lien vers un formulaire pour changer le mot de passe dans une autre US.

2020-06-21 14:30 UTC, dierickd requested changes

2020-06-21 14:30 UTC, dierickd commented on src/Entity/User.php
>       */
Peut-être qu'il faudrait définir un maxlength

2020-06-21 14:30 UTC, dierickd commented on templates/user/new.html.twig
> +{% form_theme form 'bootstrap_4_layout.html.twig' %}
Pourquoi pas définir thème bootstrap par défaut
https://symfony.com/doc/current/form/bootstrap4.html

2020-06-22 08:00 UTC, benoitchocot submitted a review, later dismissed
Y a un petit bonus sur la partie des messages flash, j'espère que ça passera :p

2020-06-22 11:54 UTC, sblondeau requested changes

2020-06-22 11:54 UTC, sblondeau commented on src/Entity/User.php
>       */
le client avait pas donné des règles ? aussi sur le pattern des password ? (ça peut venir dans une future US ceci dit)

2020-06-22 11:54 UTC, sblondeau commented on templates/user/index.html.twig
> +        <a href="{{ path('user_new') }}" class="btn" title="Nouvelle utilisateur">
Nouvel !!!

2020-06-22 11:54 UTC, sblondeau commented on webpack.config.js
>      .addEntry('projectDetails', './assets/scss/projectDetails.scss')
pour les feuilles de style, c'est plutot addStyleEntry() qu'il faut utiliser ;-) ça évite la création d'un fichier js qui ne sert à rien au moment du build

2020-06-22 13:31 UTC, dierickd approved these changes

2020-06-22 14:20 UTC, sblondeau approved these changes

2020-06-22 14:20 UTC, merged