S03 us50 user password
WildCodeSchool/orleans-php-2003-project-easterapp pull request #132
Opened 2020-06-28 13:54 UTC by dante18

2020-06-29 08:43 UTC, mayard689 submitted a review, later dismissed
Approved despite of automatic commented code into notification.html.twig

2020-06-29 13:38 UTC, sblondeau requested changes

2020-06-29 13:38 UTC, sblondeau commented on assets/scss/security.scss
> +    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
c'est pas parce que tu fais du rgba que ce n'est pas une couleur => donc variable 
idem pour le background #fff 2 lignes au dessus. 
Fais attention, ça doit faire la 10ème fois que je te jette une PR à cause de ça, c'est un peu bête ! ;-)

2020-06-29 13:38 UTC, sblondeau commented on src/Entity/User.php
>       * @ORM\Column(type="string", length=180, unique=true)
manque l'Assert\Email
et pourquoi as tu retirer l'assert Length max 100 ?

2020-06-29 13:38 UTC, sblondeau commented on src/Entity/User.php
>       * @ORM\Column(type="string")
assert length NotBlank et Lenth max 255 ?

2020-06-29 13:38 UTC, sblondeau commented on src/Entity/User.php
>       * @ORM\Column(type="string")
en fait tu as retirer les Assert partout je comprends pas bien pourquoi

2020-06-29 13:38 UTC, sblondeau commented on src/Form/UserType.php
> +                    new NotBlank([
aaahhh mais tu as remis toutes les contraintes là ? pourquoi ? utilises les @Assert !
dans le code généré il te met les verif direct dans le form pour ne pas etre dépendant du système d'annotation, mais là on l'utilise au contraire au maximum...

2020-06-29 13:38 UTC, sblondeau commented on templates/security/changepassword.html.twig
> +                        <p class="pb-2">Le mot de passe doit contenir 8 caractères, dont 1
c'est pas obligatoire, mais c'est clairement le type d'info que tu peux afficher via {{form_help(form.password}} sous le champ corresondant. Et dans ton form tu ajoutes l'option "help"

2020-06-29 13:38 UTC, sblondeau commented on templates/user/notification/notification.html.twig
> +<!doctype html>
c'est quoi ce fichier ? quelle utilité ?

2020-06-29 13:38 UTC, sblondeau commented on templates/user/notification/mjml/notification.html.twig
> +<mjml>
pourquoi tu t'embetes à partir sur du mjml, alors que c'est juste un mail de reset de password pour l'utilisation d'une appli interne... c'est vraiment pas nécessaire !

2020-06-29 16:33 UTC, dante18 commented on src/Form/UserType.php
> +                    new NotBlank([
Lors de la création d'un utilisateur on fait appel à deux formulaires, l'un pour créer le compte et l'autre pour que l'utilisateur modifie le mot de passe généré par défaut par l'administrateur. Lors de la vérification des formulaires, symfony vérifie les champs présents, plus ceux dont je n'avais pas besoin et qui n'apparaissent pas dans la page en utilisant les asserts que j'avais mis dans le fichier User.php. J'ai donc retiré les asserts et j'ai mis des contraintes dans le générateur de formulaire pour que les vérifications se fassent.

2020-06-30 09:12 UTC, dierickd requested changes

2020-06-30 09:12 UTC, dierickd commented on src/Entity/User.php
>       */
Je ne vois pas Assert\Email, peut-être le rajouter serait plus juste

2020-06-30 09:14 UTC, mayard689 submitted a review, later dismissed

2020-06-30 09:35 UTC, dierickd approved these changes

2020-06-30 10:25 UTC, sblondeau approved these changes

2020-06-30 10:25 UTC, merged