now possible to add the feature on the selected project variant
WildCodeSchool/orleans-php-2003-project-easterapp pull request #154
Opened 2020-07-01 05:42 UTC by mayard689

2020-07-01 06:58 UTC, benoitchocot submitted a review, later dismissed

2020-07-01 08:26 UTC, sblondeau requested changes

2020-07-01 08:26 UTC, sblondeau commented on src/Form/SpecificFeatureType.php
> +            ->add('isMiddle', CheckboxType::class, ['mapped' => false, 'required' => false, 'label' => 'Middle'])
t'as sans doute une bonne raison, mais pourquoi il est mapped => false ? 
en fait c'est pas plutot sensé venir hydrater un ProjetFeature ce form (et éventuellement inclure un FeatureType) ?

2020-07-01 09:38 UTC, mayard689 commented on src/Form/SpecificFeatureType.php
> +            ->add('isMiddle', CheckboxType::class, ['mapped' => false, 'required' => false, 'label' => 'Middle'])
C'est mapped => false parce que les propriétés isXxx n'apparitennnet pas à l'entité feature. Je n'ai pas essayé mais selon moi je devrait me faire jeter si je ne de-mappe pas le champ.

Cette methode consiste à creer une feature. Et le controleur relie la feature au project en créant l'objet de mise en relation "projectFeature". Et le projectFeature aura besoin des infos isXxx.

2020-07-02 16:38 UTC, sblondeau approved these changes

2020-07-02 16:39 UTC, merged