S05 us53 update user
WildCodeSchool/orleans-php-2003-project-easterapp pull request #155
Opened 2020-07-01 08:46 UTC by dante18

2020-07-01 15:00 UTC, dierickd submitted a review, later dismissed

2020-07-01 19:17 UTC, sblondeau requested changes

2020-07-01 19:17 UTC, sblondeau commented on src/Form/ChangeRoleType.php
> +                    'Utilisateur' => 'ROLE_APPUSER',
fais plutot une constante pour stocker ton tableau de roles, constante que tu peux réutiliser dans un @Assert\Choice au niveau de $roles dans l'entité User

2020-07-02 17:25 UTC, dierickd approved these changes

2020-07-03 07:52 UTC, sblondeau approved these changes

2020-07-03 07:52 UTC, merged