S05 us26 user connection
WildCodeSchool/orleans-php-2003-project-easterapp pull request #156
Opened 2020-07-01 13:25 UTC by dante18

2020-07-01 15:04 UTC, dierickd requested changes

2020-07-01 15:04 UTC, dierickd commented on src/Controller/SecurityController.php
> +
Code commenté à retirer

2020-07-02 07:25 UTC, dierickd submitted a review, later dismissed

2020-07-02 07:25 UTC, dierickd commented on src/Controller/SecurityController.php
> +
Nous devons normalement nous connecter pour acceder au site, par logique la route devrait mener à la racine...
    /**
     * @Route("/login", name="app_login")
     */

2020-07-02 07:55 UTC, sblondeau requested changes

2020-07-02 07:55 UTC, sblondeau commented on assets/js/security.js
>  for (let i = 0; i < button.length; i++) {
que c'est compliqué ! ;-)
j'ai repris ton code, ces qq lignes font la meme chose normalement, je te laisse retester
```
const button = document.querySelector('.button_password');

button.addEventListener('click', (e) => {
    button.firstChild.classList.toggle('fa-eye');
    button.firstChild.classList.toggle('fa-eye-slash');

    let inputPassword = document.getElementById('inputPassword');
    let newInputType = inputPassword.getAttribute('type') === 'text' ? 'password' : 'text';
    inputPassword.setAttribute('type', newInputType);
});
```

2020-07-02 17:24 UTC, dierickd submitted a review, later dismissed

2020-07-03 15:23 UTC, dierickd approved these changes

2020-07-03 16:38 UTC, sblondeau approved these changes

2020-07-03 16:39 UTC, merged