S05 us51 filtres features
WildCodeSchool/orleans-php-2003-project-easterapp pull request #160
Opened 2020-07-02 10:59 UTC by benoitchocot

2020-07-02 15:56 UTC, mayard689 approved these changes

2020-07-02 16:49 UTC, sblondeau requested changes

2020-07-02 16:49 UTC, sblondeau commented on assets/js/features.js
> +function sortTable(n) {
j'aime pas du tout :p ça devrait plutot etre fait via une requete SQL et jouer sur le ORDER BY. Vous pouvez rafraichir la page c'est pas génant je trouve. Sort le tableau comme ça en manipulant le DOM je trouve pas ça hyper propre :/ 
Alors que tu fais un lien sur l'entete du tableau, qui renvoie vers la meme route avec un ?order=name&sort=asc et ça te sert à faire ta requete

2020-07-03 06:53 UTC, sblondeau commented on assets/js/features.js
> +function sortTable(n) {
et ça ne me semble pas prioritaire en plus ;-)

2020-07-08 07:28 UTC, closed without merging