added default quotation in detail project
WildCodeSchool/orleans-php-2003-project-easterapp pull request #161
Opened 2020-07-02 12:35 UTC by dierickd

2020-07-02 17:37 UTC, dante18 submitted a review, later dismissed
OK

2020-07-03 08:26 UTC, sblondeau requested changes
manque fixtures

2020-07-03 08:26 UTC, sblondeau commented on assets/scss/projectDetails.scss
>      color: grey;
couleur variable CSS...

2020-07-03 08:26 UTC, sblondeau commented on assets/scss/projectDetails.scss
> +    border-color: transparent green transparent transparent;
couleur variable css

2020-07-03 08:26 UTC, sblondeau commented on assets/scss/projectDetails.scss
> +.nav-tabs .default::after {
j'ai testé la page. Bonne idée la marque visuelle pour identifier le tab actif, mais tu devrais te baser sur les styles de base de bootstrape en prio https://getbootstrap.com/docs/4.5/components/navs/#tabs pour indiquer la tab active
tu peux ajouter un truc en plus si tu veux, mais là je trouve pas le rendu suffisamment "net" pour bien identifier la tab active.

2020-07-04 16:28 UTC, dante18 approved these changes
OK

2020-07-05 20:48 UTC, sblondeau approved these changes

2020-07-05 20:50 UTC, merged