S05 us32 reset user password
WildCodeSchool/orleans-php-2003-project-easterapp pull request #181
Opened 2020-07-05 09:34 UTC by dante18

2020-07-05 10:14 UTC, dierickd approved these changes

2020-07-06 06:59 UTC, sblondeau requested changes

2020-07-06 06:59 UTC, sblondeau commented on templates/security/security.html.twig
> +        {% block body %}
pourquoi cette page n'étant pas ton layout Twig comme les autres ?

2020-07-06 12:17 UTC, dante18 commented on templates/security/security.html.twig
> +        {% block body %}
Les pages login, resetPassword ont une structure différente des autres pages du site. J'ai donc créé le fichier security.html.twig qui contient le code en commun pour les pages login, resetPassword,...

2020-07-06 13:30 UTC, dierickd submitted a review, later dismissed

2020-07-06 13:38 UTC, sblondeau requested changes

2020-07-06 13:38 UTC, sblondeau commented on templates/security/security.html.twig
> +        {% block body %}
hum :/ ok mais dans ce cas tu dois au minimum extends ton fichier base ! c'est le principe de ce fichier, avoir la structure HTML de base...

les seuls cas ou "eventuellement" ça peut ne pas etre utilise de repartir de base c'est si tu fais des twig pour des mail ou des PDF ^^ donc la ton layout_security doit etendre base ainsi il aura bootstrap et autres de chargé

2020-07-06 15:57 UTC, dierickd submitted a review, later dismissed

2020-07-07 07:59 UTC, sblondeau requested changes

2020-07-07 07:59 UTC, sblondeau commented on templates/security/security.html.twig
> +    {% block notification %}
non si je te fais etendre base c'est notamment pour que tu n'ai pas à répéter le block de flash message ! il doit etre déjà dans ton base normalement

2020-07-07 18:41 UTC, mayard689 approved these changes

2020-07-08 06:54 UTC, sblondeau approved these changes

2020-07-08 06:54 UTC, merged