S05US52_show_price
WildCodeSchool/orleans-php-2003-project-easterapp pull request #183
Opened 2020-07-05 17:53 UTC by dierickd

2020-07-05 18:43 UTC, dante18 submitted a review, later dismissed
OK

2020-07-05 21:13 UTC, sblondeau requested changes

2020-07-05 21:13 UTC, sblondeau commented on templates/project/_form.html.twig
> +                <label>Totale HT : </label>
Total

2020-07-05 21:13 UTC, sblondeau commented on src/Controller/ProjectController.php
> +            'price_per_day' => self::PRICE_PER_DAY * $load,
un peu compliqué. 
je rate peut etre un truc, mais si dans la liste tu fais un 'load'=>$load ?? 0 
et 'price_per_day' => self::PRICE_PER_DAY 
(suite plus bas)

2020-07-05 21:13 UTC, sblondeau commented on templates/project/_form.html.twig
> +                        {{ price_per_day|number_format(2, '.', ' ') }} €
(suite) 
ici du coup tu pourrais enlever toute la condition if/else et faire plus que 
`{{ (price_per_day * load)|number_format(2, '.', ' ') }}€`
puisque load vaut une valeur ou 0

2020-07-06 07:34 UTC, dante18 submitted a review, later dismissed
OK

2020-07-06 13:09 UTC, dante18 approved these changes
OK

2020-07-06 13:40 UTC, sblondeau approved these changes

2020-07-06 13:40 UTC, merged