S06US17_projectIndexFigures
WildCodeSchool/orleans-php-2003-project-easterapp pull request #195
Opened 2020-07-06 21:36 UTC by mayard689

Add project cost and load to the project index table

2020-07-07 17:38 UTC, dante18 submitted a review, later dismissed
OK

2020-07-08 07:46 UTC, sblondeau requested changes

2020-07-08 07:46 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +            $highFeatures = $this->projectFeatureRepos->findProjectFeatures($project, 'high');
je crois que tu as une constante qq part VARIANTS=['low', 'middle', 'high'] qq part non ? 
donc on pourrait faire un truc du style
```
foreach(self::VARIANTS as $variant) {
  $variantFeatures[$variant] = $this->projectFeatureRepos->findProjectFeatures($project, $variant);
  $prices[$project->getId()]['load'][$variant] = $this->calculateProjectLoad($project, $variantFeatures[$variant] );
  $prices[$project->getId()]['cost'][$variant] =  ProjectController::PRICE_PER_DAY * $prices[$project->getId()]['load'][$variant];
}
```
et le number_format tu le fais seulement dans la vue à mon avis. en tout cas là ton calcul de cost se fait déjà sur un résultat arrondi niveau load, donc tu risques d'avoir une imprécision.  Fais le vraiment qu'à la fin, et dans la vue ça me parait le plus pertinent, car au moins là tu obtiens un nombre précis, que tu peux afficher ou non de manière précise.

2020-07-08 07:46 UTC, sblondeau commented on templates/project/index.html.twig
> +                    title=" <h6> High :</h6>
là pareil je pense que tu peux faire une boucle. Quite à mettre le code un peu complexe dans une autre vue twig et d'utilise un include pour ton attribut title.

2020-07-08 11:12 UTC, mayard689 commented on src/Service/ProjectCalculator.php
> +            $highFeatures = $this->projectFeatureRepos->findProjectFeatures($project, 'high');
Le tableau VARIANT n'existe plus. Pour rester dans l'esprit de ta solution, j'ai remplacé par un appel en BD.

2020-07-08 11:17 UTC, dante18 approved these changes
OK

2020-07-08 11:53 UTC, sblondeau approved these changes

2020-07-08 11:53 UTC, merged