S06 us13
WildCodeSchool/orleans-php-2003-project-easterapp pull request #200
Opened 2020-07-08 12:39 UTC by mayard689

2020-07-08 13:02 UTC, dante18 submitted a review, later dismissed
OK

2020-07-08 16:15 UTC, sblondeau requested changes

2020-07-08 16:15 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +                if (isset($synthesis['load'][$variantName][$category])) {
c'est pas très joli ce if/else je trouve (idem pour les cost plus bas)
fais plutot               
 if (!isset($synthesis['load'][$variantName][$category])) { 
      $synthesis['load'][$variantName][$category] = 0;
}
 $synthesis['load'][$variantName][$category] += $feature->getDay(); 

je trouve qu'on identifie bien mieux le cas ou on initialise, et le reste du temps on ajoute

2020-07-08 16:15 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +    {%  for featureCategory, CategorySum in projectSynthesis.load[variant] %}
categorySum

2020-07-08 16:15 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +    {%  for featureCategory, CategorySum in projectSynthesis.load[variant] %}
mais en fait tu l'utilises ou ce categorySum ?

2020-07-08 16:15 UTC, sblondeau commented on src/Service/ProjectCalculator.php
> +        $synthesis=[
c'est pas utile de l'initialiser là je pense, non ?

2020-07-08 19:11 UTC, mayard689 commented on src/Service/ProjectCalculator.php
> +        $synthesis=[
Je ne comprends pas, où devrais je l'initialiser ? PhpStan bloque le commit si je ne l'initialise pas. Et je viens de détecter un bug lié à la non initialisation des clefs 'high' 'middle' 'low'.

2020-07-08 22:11 UTC, dierickd approved these changes

2020-07-09 08:24 UTC, sblondeau approved these changes

2020-07-09 08:24 UTC, merged