S03 us16 autocomplete list feature
WildCodeSchool/orleans-php-2003-project-easterapp pull request #202
Opened 2020-07-08 13:12 UTC by dierickd

2020-07-08 17:43 UTC, dante18 submitted a review, later dismissed
OK

2020-07-09 08:38 UTC, sblondeau requested changes

2020-07-09 08:38 UTC, sblondeau commented on assets/js/easyautocomplete.js
> +        const input = $('#feature_name')
je comprends pas bien pourquoi c'est exactement le meme code, si on est on 'input' sur le champ ou si on clique sur un li ? si on clique tu refais une requete pour recup les infos ? je suis pas sur que ce soit le plus opti mais bon.
Au minimum, fait une fonction JS avec  
```

        const input = $('#feature_name')
            .val();
        if (input.length > 2) {
            // eslint-disable-next-line no-use-before-define
            fetchFeature(input);
        } else {
            // eslint-disable-next-line no-use-before-define
            clearInput();
        } 
```
et tu rappelles la fonction dans les 2 events

2020-07-09 08:38 UTC, sblondeau commented on assets/scss/easyAutocomplete.scss
> +.easy-autocomplete {
c'est une feuille de style de base que tu n'as pas retouché ?
niveau couleur y a peut etre moyen de reutiliser les variable CSS pour que ça colle à la charte graphique ?

2020-07-09 08:38 UTC, sblondeau commented on assets/scss/easyAutocomplete.scss
> +.easy-autocomplete {
au moins à qq endroits stratégique ? à voir en fonction du rendu actuel si c'est vraiment nécessaire

2020-07-09 08:38 UTC, sblondeau commented on src/Controller/ProjectController.php
> +        $feature = $featureRepository->featureLikeSearch($input);
tu peux refaire une verif si strlen(input) > 2 comme tu fais coté JS

2020-07-09 08:38 UTC, sblondeau commented on src/Controller/ProjectController.php
> +    public function fetchFeature(string $input, FeatureRepository $featureRepository): JsonResponse
je me pose des questions sur la pertinence de cette méthode, vu que le searchFeature recup déjà un objet feature ?

2020-07-09 08:38 UTC, sblondeau commented on src/Repository/FeatureRepository.php
> +    public function featureFetch(?string $input)
c'est juste un équiv de findBy au final non ?

2020-07-09 10:12 UTC, dierickd commented on assets/js/easyautocomplete.js
> +        const input = $('#feature_name')
Lors d'un clic sur le li le chargement ne fonctionne pas si j'enléve le 'click'.

2020-07-09 21:47 UTC, sblondeau commented
dsl je te la refuse car la plupart de mes commentaires ne sont pas corrigés

2020-07-10 08:10 UTC, benoitchocot submitted a review, later dismissed

2020-07-10 08:12 UTC, sblondeau submitted a review, later dismissed

2020-07-10 08:18 UTC, sblondeau approved these changes

2020-07-10 08:18 UTC, merged