Fix Features button Style
WildCodeSchool/orleans-php-2003-project-easterapp pull request #208
Opened 2020-07-09 14:27 UTC by benoitchocot

2020-07-09 14:34 UTC, dante18 submitted a review, later dismissed
OK

2020-07-09 20:13 UTC, mayard689 submitted a review, later dismissed

2020-07-09 21:37 UTC, sblondeau requested changes

2020-07-09 21:37 UTC, sblondeau commented on assets/scss/app.scss
> +    color: #046077;
...

2020-07-09 21:37 UTC, sblondeau commented on templates/category/index.html.twig
> +            <a href="{{ path('category_new') }}">Ajouter une catégorie </a><i class="fas fa-plus-circle ml-1"></i>
pas de "a" dans un button !!! vous avez les class btn pour styliser les lien comme des boutons

2020-07-09 21:37 UTC, sblondeau commented on templates/feature/index.html.twig
> +            <a href="{{ path('feature_new') }}">Ajouter une fonctionnalité </a><i class="fas fa-plus-circle ml-1"></i>
idem

2020-07-09 21:37 UTC, sblondeau commented on templates/project/index.html.twig
> +            <a href="{{ path('project_new') }}">Ajouter un projet </a><i class="fas fa-plus-circle ml-1"></i>
+1

2020-07-10 06:15 UTC, mayard689 approved these changes

2020-07-10 06:30 UTC, sblondeau approved these changes

2020-07-10 06:30 UTC, merged