css updated
WildCodeSchool/orleans-php-2003-project-easterapp pull request #209
Opened 2020-07-09 15:35 UTC by mayard689

2020-07-09 15:40 UTC, benoitchocot submitted a review, later dismissed

2020-07-09 16:21 UTC, sblondeau submitted a review, later dismissed

2020-07-09 20:28 UTC, benoitchocot submitted a review, later dismissed

2020-07-09 21:42 UTC, sblondeau requested changes

2020-07-09 21:42 UTC, sblondeau commented on templates/project/_form.html.twig
>                          {{ variant == variantItem.name and project.quotation.name == variantItem.name ? 'active default' :
je suis perdu là. 
Entre les variantItem et les quotation.name dejà je ne sais plus trop quoi est quoi.
Mais surtout ne fait pas de condition ternaire imbriquées car ça devient totalement illisible :/

2020-07-09 23:09 UTC, mayard689 commented on templates/project/_form.html.twig
>                          {{ variant == variantItem.name and project.quotation.name == variantItem.name ? 'active default' :
Ce n'est pas moi qui ait écrit ça !

2020-07-10 06:07 UTC, benoitchocot submitted a review, later dismissed

2020-07-10 06:37 UTC, sblondeau submitted a review, later dismissed

2020-07-10 06:38 UTC, sblondeau commented on templates/project/_form.html.twig
>                          {{ variant == variantItem.name and project.quotation.name == variantItem.name ? 'active default' :
peu importe qui l'a écrit, tant que c'est corrigé ^^

2020-07-10 07:14 UTC, benoitchocot approved these changes

2020-07-10 08:12 UTC, merged