fix bug charge sur fonctionnalités
WildCodeSchool/orleans-php-2003-project-easterapp pull request #289
Opened 2020-07-15 13:08 UTC by benoitchocot

Close #242

2020-07-15 13:14 UTC, dante18 approved these changes
OK

2020-07-15 22:21 UTC, sblondeau requested changes

2020-07-15 22:21 UTC, sblondeau commented on src/Form/FeatureType.php
> +            ->add('day')
euh je vois pas pourquoi tu enlève le Type ? il faut le mettre au contraire ...

2020-07-16 04:12 UTC, benoitchocot commented on src/Form/FeatureType.php
> +            ->add('day')
Je cherchais comment n'autoriser qu'une valeur de type float, et visiblement c'était la solution la plus efficace , en tout cas ça a super bien fonctionné

2020-07-16 08:57 UTC, closed without merging