FIX_User
WildCodeSchool/orleans-php-2003-project-easterapp pull request #296
Opened 2020-07-15 14:30 UTC by dante18

2020-07-15 14:40 UTC, dierickd submitted a review, later dismissed

2020-07-15 22:27 UTC, sblondeau requested changes

2020-07-15 22:27 UTC, sblondeau commented on src/Entity/User.php
> +     *     pattern="/^([a-zA-Z'àâéèêôùûïüçÀÂÉÈÔÙÛÎÛÇ[:blank:]-]{1,75})$/",
inutile je trouve :/ 
ça ne sert pas à grand chose, au pire si ton user veux s'appeler toto45 ça n'est pas "bloquant" pour l'application. Par contre un Regex (meme s'il semble pas trop mal) est rarement exhaustif, et tu vas te retrouver à ignorer celui qui aura un "ñ" dans son nom ou autre cas particulier... mieux vaut ne pas etre trop restrictif si ça n'est pas génant pour l'utilisation du site

2020-07-16 09:45 UTC, dierickd approved these changes

2020-07-16 10:33 UTC, sblondeau requested changes

2020-07-16 10:33 UTC, sblondeau commented on src/Entity/User.php
> +     * @Assert\Regex(
non pas de Regex ! 
Là tu ne peux plus créer "Jérome" car la Regex gère pas les accents...
Je fermerais tout simplement cette PR

2020-07-16 14:44 UTC, dierickd approved these changes

2020-07-16 14:53 UTC, closed without merging