obligation choice variant when add feature in project
WildCodeSchool/orleans-php-2003-project-easterapp pull request #299
Opened 2020-07-15 15:51 UTC by dierickd

Close #298

2020-07-15 17:54 UTC, benoitchocot submitted a review, later dismissed

2020-07-15 22:28 UTC, sblondeau approved these changes

2020-07-16 07:59 UTC, dante18 submitted a review, later dismissed
OK

2020-07-16 08:32 UTC, sblondeau requested changes

2020-07-16 08:32 UTC, sblondeau commented on src/Controller/ProjectController.php
> +            if ($formFeature['isHigh']->getData() === false
hum, je pense que cette contrainte que etre mis via des @Assert  (voire avec Adrien a qui j'ai fais une remarque similaire hier ^^)
je vous laisse chercher un peu et revenez vers moi si pb

2020-07-16 15:01 UTC, dante18 approved these changes
OK

2020-07-16 16:03 UTC, sblondeau requested changes

2020-07-16 16:03 UTC, sblondeau commented on src/Entity/ProjectFeature.php
> +    public function getSelectVariant()
non l'idée est de rajouter un @Assert sur le getSelectVariant pour justement ne plus avoir à faire cette validation dans le controlleur

2020-07-17 08:27 UTC, dante18 approved these changes
OK

2020-07-17 08:28 UTC, sblondeau approved these changes

2020-07-17 08:28 UTC, merged