S01 us39 edit project feature list small
WildCodeSchool/orleans-php-2003-project-easterapp pull request #30
Opened 2020-06-05 06:48 UTC by mayard689

This add the project feature list to the project detailled page

2020-06-05 06:56 UTC, benoitchocot submitted a review, later dismissed

2020-06-05 07:25 UTC, benoitchocot submitted a review, later dismissed

2020-06-05 08:20 UTC, sblondeau requested changes

2020-06-05 08:20 UTC, sblondeau commented on assets/scss/app.scss
> +.feature-name{
devrait etre dans un fichier css séparé, pas dans app.scss qui contient le style "général"

2020-06-05 08:20 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +                <p class="feature-name">{{ project.projectFeatures[loop.index-1].feature.name}}</p>
deja tu as loop.index0 qui existe pour partir de 0
mais dans ce cas tu dois utiliser direct la variable projectFeature de ta boucle et non projectFeatures[index]

2020-06-05 08:20 UTC, sblondeau commented on src/Form/ProjectType.php
> +            ->add('projectFeatures', CollectionType::class, [
a voir si le CollectionType est le meilleur choix... c'est vrai que si on veut faire facilement un edit de plusieurs lignes en meme temps, c'est sans doute le plus pertinent. Après c'est pas ce qu'il y a de plus simple à gérer et surtout à mettre en forme ^^

2020-06-05 08:20 UTC, sblondeau commented on src/Form/ProjectType.php
> +                'entry_options' => ['label' => false],
ajoute aussi                 'label' => false,
sinon s'il n'y a pas de feature reliée à un projet, on a le label "Projet Features" qui apparait en bas du form

2020-06-05 08:20 UTC, sblondeau commented on assets/scss/app.scss
>  @import "projectDetails.scss";
cd fichier CSS ne devrait pas etre importé dans app.scss (sinon il sera chargé sur toutes les pages).
Il faut ajouter une Entry dans le fichier webpack config
 je te laisse regarder le addEntry() dans la doc (y a un exemple sur le wildzoo aussi). Mais si tu le sens pas, ça peut attendre un fix prochain, j'en parlerai plus dans le livecoding de mardi prochain (si j'y pense :D)

2020-06-05 08:20 UTC, sblondeau commented on assets/scss/projectDetails.scss
> +    input{
j'ai testé, niveau ergonomie il faut revoir les choses, c'est trop difficile de bien cliquer sur chaque champ pour l'éditer. Il faudrait ajouter du padding. Et quand on est en focus sur un champ editable, faire apparaitre le fond en plus clair et des petite border, qu'on comprenne qu'on se trouve dans un input

2020-06-05 08:28 UTC, mayard689 commented on templates/project/_featuresList.html.twig
> +                <p class="feature-name">{{ project.projectFeatures[loop.index-1].feature.name}}</p>
loop.index0 : ok
 projectFeature n'a pas de propriété name donc symfony declenche une exception si je tente de lire le name directement sur projectFeature.

2020-06-05 08:39 UTC, mayard689 commented on src/Form/ProjectType.php
> +                'entry_options' => ['label' => false],
ok, fait.

2020-06-05 08:39 UTC, mayard689 commented on src/Form/ProjectType.php
> +            ->add('projectFeatures', CollectionType::class, [
Alternatives à etudier. Mais dans l'immediat ça fonctionne bien.

2020-06-05 09:49 UTC, mayard689 commented on assets/scss/app.scss
>  @import "projectDetails.scss";
Fait !

2020-06-05 09:56 UTC, mayard689 commented on assets/scss/projectDetails.scss
> +    input{
Il faut qu'on discute de ça dans l'équipe projet.
Dans l'immediat j'ai mis une border avec la couleur primary au focus et au hover. Le clic sur le label place automatiquement le focus sur l'input.

2020-06-05 09:59 UTC, mayard689 commented on assets/scss/app.scss
> +.feature-name{
Le style des tableaux est réutilisé sur toutes les pages donc je pense qu'il est ptréférable de le laisser dans ce fichier.

Par contre le nom de la classe est trop specifique. Je le change par quelque chose de plus générique qui restera explicite dans d'autres contextes.

2020-06-09 06:06 UTC, benoitchocot approved these changes

2020-06-09 14:49 UTC, sblondeau approved these changes

2020-06-09 14:49 UTC, merged