Fix feature deletion when enter pressed
WildCodeSchool/orleans-php-2003-project-easterapp pull request #320
Opened 2020-07-20 09:44 UTC by mayard689

2020-07-20 13:32 UTC, dierickd submitted a review, later dismissed

2020-07-20 15:41 UTC, sblondeau requested changes

2020-07-20 15:41 UTC, sblondeau commented on assets/js/formEnterLocker.js
> +$(document).ready(() => {
hum
je me suis penché un peu sur le code pour comprendre d'où venait le pb... 
mettre les boutons pour delete avec les attributs formaction était peut etre pas la meilleure solution, mais bon.
Par contre, ici je pense qu'on peut faire mieux. Plutot que d'empêcher la soumission du form (il prend le bouton le plus proche par défaut apparement), fais en sorte que ce soit le form général qui soit soumis (c'est ce qu'on attend en tant qu'utilisateur, et là appuyer sur entrée reste important en terme d'UX.
Donc recupère le form (ajoute un id si c'est plus simple. et check l'envent 'submit' sur ce form (plutot que de check keydown sur la page.
Quand on submit le form, si la soumission s'est fait via l'appui sur entrée, là tu soumet bien ce form (et donc tu passes pas par les attributs formaction)
j'ai pas testé mais sur le principe ça doit fonctionner :D 
hésite pas si ce n'est pas clair

2020-07-24 11:14 UTC, benoitchocot approved these changes

2020-07-24 12:01 UTC, merged