S02 us02 create new project
WildCodeSchool/orleans-php-2003-project-easterapp pull request #64
Opened 2020-06-11 09:39 UTC by dierickd

2020-06-11 12:06 UTC, mayard689 commented on templates/project/_form.html.twig
> +            <p class="input-like"></p>
manque le {{load}}

2020-06-11 12:06 UTC, mayard689 commented on assets/scss/newProject.scss
> +.new-project .fa-plus-circle {
est ce qu'il ne faudrait pas appeler la class ".new project" ".add-item" et mettre ça dans app.scss pour que tous les boutons add utilisent le meme css.

2020-06-11 12:06 UTC, mayard689 commented on templates/project/new.html.twig
> -    {{ include('project/_form.html.twig') }}
il faut include ce /_form.thml.twig plutot que de le recopier

2020-06-11 12:06 UTC, mayard689 commented on templates/project/new.html.twig
> +        <button class="btn btn-primary form-btn">Créer le projet</button>
Le label de ce bouton peut être passé en paramètre à l'include. Il est possible de définir une variable twig avant le include et d'utiliser cette variable dans le fichier inclus. et le mettre le contenu dans le label du bouton

2020-06-11 12:07 UTC, dierickd commented on templates/project/_form.html.twig
> +            <p class="input-like"></p>
Résolu

2020-06-11 12:07 UTC, dierickd commented on assets/scss/newProject.scss
> +.new-project .fa-plus-circle {
Résolu, fichier créé pour l'occasion

2020-06-11 13:16 UTC, dierickd commented on templates/project/_form.html.twig
> +            <p class="input-like"></p>
Done modif faite => {{ load ?? 0 }}

2020-06-11 13:17 UTC, dierickd commented on templates/project/new.html.twig
> -    {{ include('project/_form.html.twig') }}
done, fichier inclu et séparation des buttons

2020-06-11 13:17 UTC, dierickd commented on templates/project/new.html.twig
> +        <button class="btn btn-primary form-btn">Créer le projet</button>
modification de la structure

2020-06-11 15:57 UTC, sblondeau requested changes

2020-06-11 15:57 UTC, sblondeau commented on templates/project/edit.html.twig
> +            {{ include('project/_buttonEditProject.html.twig') }}
hum... je pense comprendre ton idée de fichier inclu, c'est une question de mise en page ?
dans tous les cas, tes deux fichiers on quasi le meme code, or, tu peux envoyer une variable à un fichier inclus avec 
{% include('...' with {'buttonName' : 'Enregistrer} %}
https://twig.symfony.com/doc/2.x/tags/include.html
l'idée c'est que tu peux avoir un seul fichier twig au lieu de deux ;-)

2020-06-11 15:57 UTC, sblondeau commented on templates/project/index.html.twig
> +    {{ encore_entry_link_tags('app') }}
ne faudrait-il pas appeler newProjet après app si besoin de le surcharger ?

2020-06-11 15:57 UTC, sblondeau commented on templates/project/new.html.twig
> +    {{ encore_entry_link_tags('app') }}
idem ici inverser je pense

2020-06-11 16:18 UTC, dierickd commented on templates/project/edit.html.twig
> +            {{ include('project/_buttonEditProject.html.twig') }}
Modif faite, merci pour include

2020-06-11 18:46 UTC, benoitchocot submitted a review, later dismissed

2020-06-12 07:21 UTC, sblondeau requested changes

2020-06-12 07:21 UTC, sblondeau commented on templates/project/index.html.twig
> +    {{ encore_entry_link_tags('app') }}
tu n'as pas modif ici

2020-06-12 08:16 UTC, dante18 approved these changes
OK

2020-06-12 08:46 UTC, sblondeau approved these changes

2020-06-12 08:46 UTC, merged