S02US08
WildCodeSchool/orleans-php-2003-project-easterapp pull request #72
Opened 2020-06-11 21:41 UTC by mayard689

2020-06-12 06:13 UTC, benoitchocot submitted a review, later dismissed

2020-06-12 08:09 UTC, benoitchocot submitted a review, later dismissed

2020-06-15 07:19 UTC, sblondeau requested changes

2020-06-15 07:19 UTC, sblondeau commented on src/Controller/ProjectController.php
> +     * @Route("Project/{id}/addFeature", name="project_feature_add", methods={"GET", "POST"})
nommage des route plutot
"project/{id}/add-feature"
voire traduire en français si client préfère ?

2020-06-15 07:19 UTC, sblondeau commented on src/Entity/Feature.php
> +     * @ORM\Column(type="boolean")
ajouter Assert type bool

2020-06-15 07:19 UTC, sblondeau commented on src/DataFixtures/FeatureFixtures.php
> +            $feature->setIsStandard(true);
prévois tu des fixtures ou tu mets justement des features avec isStandart à false également ?

2020-06-15 13:35 UTC, mayard689 commented on src/Controller/ProjectController.php
> +     * @Route("Project/{id}/addFeature", name="project_feature_add", methods={"GET", "POST"})
corrigé

2020-06-15 14:50 UTC, mayard689 commented on src/Entity/Feature.php
> +     * @ORM\Column(type="boolean")
corrigé

2020-06-15 14:53 UTC, mayard689 commented on src/DataFixtures/FeatureFixtures.php
> +            $feature->setIsStandard(true);
En fait, je n'avais pas prévu de fixture sur des features nonStandard parce que c'est un peu galère de creer une liste de feature qui ne pourront être affecté qu'a un seul projet sachant que cette association se fait via la table projectFeature...

Mais c'est fait ! J'ai la featureFixture créé maintenant une liste de feature destinées à être associées à un seul projet. Et les fixtures de projectFeature sont mises à jour pour réaliser cette association unique.

2020-06-15 15:06 UTC, benoitchocot submitted a review, later dismissed

2020-06-15 16:08 UTC, sblondeau requested changes
qq details sur les fixtures 
évite de faire des findAll dans tes fixtures
le code est optimisable mais perd pas trop de temps là dessus non plus c'est pas le plus important ;-)

2020-06-15 16:08 UTC, sblondeau commented on src/DataFixtures/FeatureFixtures.php
> +    private static $projectFeatureNumber=0;
fait une constante plutot

2020-06-15 16:08 UTC, sblondeau commented on src/DataFixtures/FeatureFixtures.php
> +        self::$projectFeatureNumber=5*$projectNumber;
pas très académique ça :D créé une variable et utilise la constante (voir plus haut)

2020-06-15 16:08 UTC, sblondeau commented on src/DataFixtures/FeatureFixtures.php
>          $categories= $manager->getRepository(Category::class)->findAll();
reutilises ton   $categoryMaxIndex=count(CategoryFixtures::CATEGORIES)-1;

2020-06-15 19:09 UTC, mayard689 commented on src/DataFixtures/FeatureFixtures.php
> +    private static $projectFeatureNumber=0;
Je ne comprends pas. 0 n'estp as une valeur fixe. La valeur est redéfinie par des expressions lignes 45 et 46. Je ne crois pas pouvoir utiliser une expression pour affecter une valeur à une constante. Si ?

Par contre c'est vrai quoi n'importe qui peut acceder à cette valeur n'importe où. Il me semble plutôt que je devrai encapsuler le calcul à l'interieur du getter (getter qui est nécessaire pour passer la valeur aux projectFixtures).

2020-06-15 19:10 UTC, mayard689 commented on src/DataFixtures/FeatureFixtures.php
> +        self::$projectFeatureNumber=5*$projectNumber;
Du coup j'ai mis le calcul dans le getter. Je recupere la valeur dans une variable juste avant de boucler pour éviter de faire le calcul à chaque iteration.

2020-06-15 19:10 UTC, mayard689 commented on src/DataFixtures/FeatureFixtures.php
>          $categories= $manager->getRepository(Category::class)->findAll();
fait

2020-06-16 08:01 UTC, benoitchocot approved these changes

2020-06-16 13:42 UTC, sblondeau approved these changes

2020-06-16 13:42 UTC, merged