S03 us44 pagination project list
WildCodeSchool/orleans-php-2003-project-easterapp pull request #94
Opened 2020-06-17 10:12 UTC by dierickd

2020-06-17 13:18 UTC, mayard689 requested changes

2020-06-17 13:18 UTC, mayard689 commented on src/Entity/Project.php
> +     * @ORM\ManyToOne(targetEntity=Application::class, inversedBy="project")
C'est bien projects avec un s puisqu'on est en relation manyToOne. Coté application, la propriété est bien 'projects' également avec un s

2020-06-17 13:27 UTC, mayard689 submitted a review, later dismissed

2020-06-17 19:08 UTC, sblondeau requested changes

2020-06-17 19:08 UTC, sblondeau commented on assets/scss/_paginator.scss
> +    background-color: transparent;
transparent c'est une couleur... => variable :p

2020-06-17 19:08 UTC, sblondeau commented on src/Controller/ProjectController.php
> +                10
j'imagine que ton 10 c'est ton max par page ? tu devrais utiliser un paramètre (à config dans le fichier service.yaml) ou une constance de classe. Mais pas en dur ;-)

2020-06-18 07:34 UTC, dierickd commented on assets/scss/_paginator.scss
> +    background-color: transparent;
changé pour une variable ;)

2020-06-18 07:35 UTC, dierickd commented on src/Controller/ProjectController.php
> +                10
comme suggéré, modifé par une constante de class

2020-06-18 07:55 UTC, dante18 approved these changes
OK

2020-06-18 12:19 UTC, sblondeau approved these changes

2020-06-18 12:19 UTC, merged