bugs solved
WildCodeSchool/orleans-php-2003-project-easterapp pull request #95
Opened 2020-06-17 11:33 UTC by mayard689

2020-06-17 13:26 UTC, dante18 submitted a review, later dismissed
OK

2020-06-17 16:05 UTC, sblondeau requested changes

2020-06-17 16:05 UTC, sblondeau commented on src/Controller/ProjectController.php
> +        Request $request,
a refacto

2020-06-17 16:05 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +<button class="btn btn-sm btn-primary float-right " formmethod="POST" formaction="{{ path('project_validate', {'id':project.id?:'-1'}) }}">
je te laisse regarder ça ;-) 
https://symfony.com/doc/current/form/multiple_buttons.html

2020-06-17 21:23 UTC, mayard689 commented on src/Controller/ProjectController.php
> +        Request $request,
Fait. Methode supprimée, reutilisation du edit et du add

2020-06-17 21:24 UTC, mayard689 commented on templates/project/_featuresList.html.twig
> +<button class="btn btn-sm btn-primary float-right " formmethod="POST" formaction="{{ path('project_validate', {'id':project.id?:'-1'}) }}">
Fait. Attention, necessite que le bouton soit intégré dans le form type.

2020-06-18 07:57 UTC, dierickd submitted a review, later dismissed

2020-06-18 08:12 UTC, benoitchocot approved these changes

2020-06-18 08:13 UTC, dierickd approved these changes

2020-06-18 15:08 UTC, sblondeau requested changes

2020-06-18 15:08 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +    {% for featureCategory in featureCategories??{} %}
pouquoi le "?? {} "

2020-06-18 15:08 UTC, sblondeau commented on templates/feature/_form.html.twig
> +        {%  set route = path('project_edit', {'id':id}) %}
je suis pas certain que ce soit la meilleure façon de faire.
ok il faut etre DRY, mais là je ne suis pas sur qu'il faille forcément viser à réutiliser le meme templamte pour le form, car dans un cas il sera sur une page à part, dans l'autre cas il sera sans doute géré à terme en ajax ou via une modale... donc pas sûr que ça soit la bonne voie... garde comme ça si tu veux pour le moment mais faudra peut etre "casser" ;-) 
c'est bien d'utiliser le meme FormType mais pas forcément la meme vue ^^

2020-06-18 15:08 UTC, sblondeau commented on src/Controller/ProjectController.php
> +            'id'=>$project->getId(),
pour ce que tu veut en faire, je passerai directement $project plutot que juste l'id

2020-06-19 06:37 UTC, mayard689 commented on templates/project/_featuresList.html.twig
> +    {% for featureCategory in featureCategories??{} %}
La création d'un projet déclenche deux bugs :+1:

2020-06-22 09:02 UTC, mayard689 commented on templates/feature/_form.html.twig
> +        {%  set route = path('project_edit', {'id':id}) %}
Les deux vues servent à creer une fonctionnalité. La différence est seulement que sur une vue la fonctionnalité a le isStandard=true et l'autre a le isStandard=false. Pour moi il faut reprendre la vue et tout ce qui vient avec (JS) et si l'une évolue, l'autre doit évoluer avec.

L'interface qui sert à aller piocher des fonctionnalités dans la liste, c'est autre chose.

2020-06-22 09:09 UTC, mayard689 commented on src/Controller/ProjectController.php
> +            'id'=>$project->getId(),
Il y a pas mal de manières de faire mais je ne vois pas vraiment ce que ça apporte de passer $project au lieu de l'id. Qu'est ce que tu entends par  "pour ce que tu veux en faire" ?

2020-06-22 10:16 UTC, benoitchocot approved these changes

2020-06-22 11:42 UTC, sblondeau requested changes

2020-06-22 11:42 UTC, sblondeau commented on templates/feature/_form.html.twig
> +        {%  set route = path('project_edit', {'id':id}) %}
J'ai l'impressin que dans un cas, c'est l'interface d'ajout depuis un projet, dans un autre cas depuis le crud des feateures non ? 
Mais bon ok, tu as mieux le projet en tête que moi, donc je te fais confiance là dessus

2020-06-22 11:42 UTC, sblondeau commented on templates/project/_featuresList.html.twig
> +    {% for featureCategory in featureCategories??{} %}
Je voulais dire que je ne voyais pas trop dans quel cas on avait un featureCategories qui serait "non transmis" :/

2020-06-22 13:45 UTC, dierickd approved these changes

2020-06-22 14:18 UTC, sblondeau approved these changes

2020-06-22 14:18 UTC, merged